version: '3'
services:
  app:
    image: reserva-app
    build:
      context: .
    ports:
      - "8092:8092"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@bdejercicios_tp?TNS_ADMIN=/app/wallet
      - SPRING_DATASOURCE_USERNAME=FSI_SUMATIVA2
      - SPRING_DATASOURCE_PASSWORD=FSI-Sumativa2
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.driver.OracleDriver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
      - SPRING_JPA_SHOW_SQL=true
      - TNS_ADMIN=/app/wallet
    networks:
      - default

networks:
  default:
    driver: bridge